### Basic Data Preprocessing for Generative AI

In [4]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

In [5]:
# Generate synthetic data
data = np.random.randint(0, 255, (10, 5))
print("Original Data:\n", data)

Original Data:
 [[196   7  94   9  55]
 [ 40 143 186  28 145]
 [121 206 178 135 157]
 [240   9  91  84  20]
 [ 95  14   8 123  31]
 [ 75 228 237  50 240]
 [ 68 118 172  41 167]
 [ 23 176 182  31  53]
 [  8  96  92 138  32]
 [ 83  42 151 186  75]]


In [6]:
# Scale data between 0 and 1
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)
print("Scaled Data:\n", scaled_data)

Scaled Data:
 [[0.81034483 0.         0.37554585 0.         0.15909091]
 [0.13793103 0.61538462 0.77729258 0.10734463 0.56818182]
 [0.48706897 0.90045249 0.74235808 0.71186441 0.62272727]
 [1.         0.00904977 0.36244541 0.42372881 0.        ]
 [0.375      0.03167421 0.         0.6440678  0.05      ]
 [0.2887931  1.         1.         0.23163842 1.        ]
 [0.25862069 0.50226244 0.71615721 0.18079096 0.66818182]
 [0.06465517 0.76470588 0.75982533 0.12429379 0.15      ]
 [0.         0.40271493 0.36681223 0.72881356 0.05454545]
 [0.32327586 0.15837104 0.62445415 1.         0.25      ]]
